name: Hello World
on: workflow_dispatch
jobs: 
  build: 
   runs-on: ubuntu-latest
   steps:
     - name: Print hello world
       run: echo "this is build job"

  Test: 
   runs-on: ubuntu-latest
   needs: build
   steps:
     - name: Print hello world
       run: echo "this is test job"
  
  Deploy: 
   runs-on: ubuntu-latest
   needs: Test
   steps:
     - name: Print hello world
       run: echo "this is Deploy job"
        
        
